##########################################
#                                        #
# This is the jekyll configuration file. #
#                                        #
##########################################

source:      ./website
destination: ./website/_site
exclude:     ['README.md', './public/sass', 'config.rb']
sass:
    style:   nested # set to nested for debugging # TODO: set to compressed

baseurl:     /MiniLinux
future:      true
lsi:         false
highlighter: rouge
markdown:    redcarpet
permalink:   pretty
