# safe:        false
# auto:        true
baseurl:    /
url: http://localhost:4000

source:      .
destination: ./_site

exclude:     ['README.md', './public/sass', 'config.rb']

# future:      true
# lsi:         false
highlighter: rouge
markdown:    redcarpet
permalink:   pretty

port: 8080
host: 0.0.0.0
